TeoCCl library: teo::Queue Class Reference
teo::Queue Class Reference
#include <queue.hpp>
Public Member Functions
Queue ()
virtual ~Queue ()
int freeAll ()
teoQueueData * newData (void *data, size_t data_length)
teoQueueData * newData (std::string data)
template<typename T >
teoQueueData * newData (const T &data)
int freeData (teoQueueData *qd)
teoQueueData * add (void *data, size_t data_length)
teoQueueData * add (const std::string &data)
template<typename T >
teoQueueData * add (const T &data)
teoQueueData * addTop (void *data, size_t data_length)
teoQueueData * addTop (std::string data)
template<typename T >
teoQueueData * addTop (const T &data)
teoQueueData * addAfter (void *data, size_t data_length, teoQueueData *after)
teoQueueData * addAfter (std::string data, teoQueueData *after)
template<typename T >
teoQueueData * addAfter (const T &data, teoQueueData *after)
teoQueueData * remove (teoQueueData *qd)
int del (teoQueueData *qd)
int delFirst ()
int delLast ()
teoQueueData * moveToTop (teoQueueData *qd)
teoQueueData * moveToEnd (teoQueueData *qd)
teoQueueData * put (teoQueueData *qd)
size_t size ()
teoQueueIterator * iterator ()
teoQueueData * iteratorNext (teoQueueIterator *it)
teoQueueData * iteratorPrev (teoQueueIterator *it)
teoQueueData * iteratorElement (teoQueueIterator *it)
teoQueueIterator * iteratorElement (teoQueueIterator *it, Queue *q=NULL)
int iteratorFree (teoQueueIterator *it)
int foreach (teoQueueForeachFunction callback, void *user_data=NULL)
Static Public Member Functions
template<typename T >
static T getData (void *data)
Constructor & Destructor Documentation
Queue()
teo::Queue::Queue () inline
References teoQueueNew().
~Queue()
virtual teo::Queue::~Queue () inline virtual
References teoQueueDestroy().
Member Function Documentation
add() [1/3]
teoQueueData* teo::Queue::add (void * data, size_t data_length) inline
References teoQueueAdd().
Referenced by add().
add() [2/3]
teoQueueData* teo::Queue::add (const std::string & data) inline
References add().
add() [3/3]
template<typename T > teoQueueData* teo::Queue::add (const T & data) inline
References add().
addAfter() [1/3]
teoQueueData* teo::Queue::addAfter (void * data, size_t data_length, teoQueueData * after) inline
References teoQueueAddAfter().
Referenced by addAfter().
addAfter() [2/3]
teoQueueData* teo::Queue::addAfter (std::string data, teoQueueData * after) inline
References addAfter().
addAfter() [3/3]
template<typename T > teoQueueData* teo::Queue::addAfter (const T & data, teoQueueData * after) inline
References addAfter().
addTop() [1/3]
teoQueueData* teo::Queue::addTop (void * data, size_t data_length) inline
References teoQueueAddTop().
Referenced by addTop().
addTop() [2/3]
teoQueueData* teo::Queue::addTop (std::string data) inline
References addTop().
addTop() [3/3]
template<typename T > teoQueueData* teo::Queue::addTop (const T & data) inline
References addTop().
del()
int teo::Queue::del (teoQueueData * qd) inline
References teoQueueDelete().
delFirst()
int teo::Queue::delFirst () inline
References teoQueueDeleteFirst().
delLast()
int teo::Queue::delLast () inline
References teoQueueDeleteLast().
foreach()
int teo::Queue::foreach (teoQueueForeachFunction callback, void * user_data = NULL) inline
References teoQueueForeach().
freeAll()
int teo::Queue::freeAll () inline
References teoQueueFree().
freeData()
int teo::Queue::freeData (teoQueueData * qd) inline
getData()
template<typename T > static T teo::Queue::getData (void * data) inline static
iterator()
teoQueueIterator* teo::Queue::iterator () inline
References teoQueueIteratorNew().
iteratorElement() [1/2]
teoQueueData* teo::Queue::iteratorElement (teoQueueIterator * it) inline
References teoQueueIteratorElement().
iteratorElement() [2/2]
teoQueueIterator* teo::Queue::iteratorElement (teoQueueIterator * it, Queue * q = NULL) inline
References teoQueueIteratorReset().
iteratorFree()
int teo::Queue::iteratorFree (teoQueueIterator * it) inline
References teoQueueIteratorFree().
iteratorNext()
teoQueueData* teo::Queue::iteratorNext (teoQueueIterator * it) inline
References teoQueueIteratorNext().
iteratorPrev()
teoQueueData* teo::Queue::iteratorPrev (teoQueueIterator * it) inline
References teoQueueIteratorPrev().
moveToEnd()
teoQueueData* teo::Queue::moveToEnd (teoQueueData * qd) inline
References teoQueueMoveToEnd().
moveToTop()
teoQueueData* teo::Queue::moveToTop (teoQueueData * qd) inline
References teoQueueMoveToTop().
newData() [1/3]
teoQueueData* teo::Queue::newData (void * data, size_t data_length) inline
References teoQueueNewData().
Referenced by newData().
newData() [2/3]
teoQueueData* teo::Queue::newData (std::string data) inline
References newData().
newData() [3/3]
template<typename T > teoQueueData* teo::Queue::newData (const T & data) inline
References newData().
put()
teoQueueData* teo::Queue::put (teoQueueData * qd) inline
References teoQueuePut().
remove()
teoQueueData* teo::Queue::remove (teoQueueData * qd) inline
References teoQueueRemove().
size()
size_t teo::Queue::size () inline
References teoQueueSize().
The documentation for this class was generated from the following file:
queue.hpp