TeoCCl library: teo::Map Class Reference
teo::Map Class Reference
#include <map.hpp>
Public Member Functions
Map ()
Map (size_t size, int auto_resize_f)
virtual ~Map ()
size_t size ()
void mapClear ()
void * getFirst (size_t *data_length)
void * add (void *key, size_t key_length, void *data, size_t data_length)
void * add (const std::string &key, const std::string &data)
template<typename D >
void * add (const std::string &key, const D &data)
template<typename K , typename D >
void * add (const K &key, const D &data)
void * get (void *key, size_t key_length, size_t *data_length)
void * get (const std::string &key, size_t *data_length)
template<typename K >
void * get (const K &key, size_t *data_length)
int del (void *key, size_t key_length)
int del (const std::string &key)
template<typename K >
int del (const K &key)
teoMapIterator * iterator ()
teoMapIterator * iteratorReverse ()
teoMapElementData * iteratorNext (teoMapIterator *it)
teoMapElementData * iterator_prev (teoMapIterator *it)
int iteratorFree (teoMapIterator *it)
teoMapElementData * mapItEl (teoMapIterator *it)
template<typename D >
D * mapItElKey (teoMapElementData *el, size_t *key_length=NULL)
template<typename D >
D * mapItElData (teoMapElementData *el, size_t *data_length=NULL)
int foreach (teoMapForeachFunction callback, void *user_data=NULL)
Constructor & Destructor Documentation
teo::Map::Map () inline
References HASH_TABLE_SIZE, and teoMapNew().
teo::Map::Map (size_t size, int auto_resize_f) inline
References teoMapNew().
virtual teo::Map::~Map () inline virtual
References teoMapDestroy().
Member Function Documentation
void* teo::Map::add (void * key, size_t key_length, void * data, size_t data_length) inline
References teoMapAdd().
Referenced by add().
void* teo::Map::add (const std::string & key, const std::string & data) inline
References add().
template<typename D > void* teo::Map::add (const std::string & key, const D & data) inline
References add().
template<typename K , typename D > void* teo::Map::add (const K & key, const D & data) inline
References add().
int teo::Map::del (void * key, size_t key_length) inline
References teoMapDelete().
Referenced by del().
int teo::Map::del (const std::string & key) inline
References del().
template<typename K > int teo::Map::del (const K & key) inline
References del().
int teo::Map::foreach (teoMapForeachFunction callback, void * user_data = NULL) inline
References teoMapForeach().
void* teo::Map::get (void * key, size_t key_length, size_t * data_length) inline
References teoMapGet().
void* teo::Map::get (const std::string & key, size_t * data_length) inline
template<typename K > void* teo::Map::get (const K & key, size_t * data_length) inline
void* teo::Map::getFirst (size_t * data_length) inline
References teoMapGetFirst().
teoMapIterator* teo::Map::iterator () inline
References teoMapIteratorNew().
teoMapElementData* teo::Map::iterator_prev (teoMapIterator * it) inline
References teoMapIteratorPrev().
int teo::Map::iteratorFree (teoMapIterator * it) inline
References teoMapIteratorFree().
teoMapElementData* teo::Map::iteratorNext (teoMapIterator * it) inline
References teoMapIteratorNext().
teoMapIterator* teo::Map::iteratorReverse () inline
References teoMapIteratorReverseNew().
void teo::Map::mapClear () inline
References teoMapClear().
teoMapElementData* teo::Map::mapItEl (teoMapIterator * it) inline
template<typename D > D* teo::Map::mapItElData (teoMapElementData * el, size_t * data_length = NULL) inline
template<typename D > D* teo::Map::mapItElKey (teoMapElementData * el, size_t * key_length = NULL) inline
size_t teo::Map::size () inline
References teoMapSize().
The documentation for this class was generated from the following file:
map.hpp