TeoCCl library: deque.h File Reference
deque.h File Reference
#include <stdlib.h>
Typedefs
typedef struct ccl_deque ccl_deque_t
Functions
ccl_deque_t * cclDequeInit (const size_t data_size)
int cclDequeSize (const ccl_deque_t *deq)
int cclDequeEmpty (const ccl_deque_t *deq)
int cclDequeTrim (ccl_deque_t *deq)
int cclDequePushFront (ccl_deque_t *deq, void *const data)
int cclDequePushBack (ccl_deque_t *deq, void *const data)
int cclDequePopFront (ccl_deque_t *deq, void *const data)
int cclDequePopBack (ccl_deque_t *deq, void *const data)
int cclDequeSetFirst (ccl_deque_t *deq, void *const data)
int cclDequeSetAt (ccl_deque_t *deq, int idx, void *const data)
int cclDequeSetLast (ccl_deque_t *deq, void *const data)
int cclDequeGetFirst (ccl_deque_t *deq, void *data)
int cclDequeGetAt (ccl_deque_t *deq, int idx, void *data)
int cclDequeGetLast (ccl_deque_t *deq, void *data)
int cclDequeClear (ccl_deque_t *deq)
void cclDequeDestroy (ccl_deque_t *deq)
Detailed Description
Author
max mpano.nosp@m.91@g.nosp@m.mail..nosp@m.com
deque container
Created on Tue Jul 11 19:55:30 2019
Typedef Documentation
typedef struct ccl_deque ccl_deque_t
Function Documentation
int cclDequeClear (ccl_deque_t * deq)
References ccl_malloc().
Referenced by cclQueClear(), and cclStackClear().
void cclDequeDestroy (ccl_deque_t * deq)
Referenced by cclQueDestroy(), and cclStackDestroy().
int cclDequeEmpty (const ccl_deque_t * deq)
References cclDequeSize().
Referenced by cclDequePopBack(), cclDequePopFront(), cclQueEmpty(), and cclStackEmpty().
int cclDequeGetAt (ccl_deque_t * deq, int idx, void * data)
References cclDequeSize().
Referenced by cclDequeGetFirst(), and cclDequeGetLast().
int cclDequeGetFirst (ccl_deque_t * deq, void * data)
References cclDequeGetAt().
Referenced by cclQueFront().
int cclDequeGetLast (ccl_deque_t * deq, void * data)
References cclDequeGetAt(), and cclDequeSize().
Referenced by cclQueBack(), and cclStackTop().
ccl_deque_t* cclDequeInit (const size_t data_size)
References ccl_malloc().
Referenced by cclQueInit(), and cclStackInit().
int cclDequePopBack (ccl_deque_t * deq, void *const data)
References cclDequeEmpty().
Referenced by cclStackPop().
int cclDequePopFront (ccl_deque_t * deq, void *const data)
References cclDequeEmpty().
Referenced by cclQuePop().
int cclDequePushBack (ccl_deque_t * deq, void *const data)
References ccl_malloc(), and ccl_realloc().
Referenced by cclQuePush(), and cclStackPush().
int cclDequePushFront (ccl_deque_t * deq, void *const data)
References ccl_malloc(), and ccl_realloc().
int cclDequeSetAt (ccl_deque_t * deq, int idx, void *const data)
References cclDequeSize().
Referenced by cclDequeSetFirst(), and cclDequeSetLast().
int cclDequeSetFirst (ccl_deque_t * deq, void *const data)
References cclDequeSetAt().
int cclDequeSetLast (ccl_deque_t * deq, void *const data)
References cclDequeSetAt(), and cclDequeSize().
int cclDequeSize (const ccl_deque_t * deq)
Referenced by cclDequeEmpty(), cclDequeGetAt(), cclDequeGetLast(), cclDequeSetAt(), cclDequeSetLast(), cclQueSize(), and cclStackSize().
int cclDequeTrim (ccl_deque_t * deq)
References ccl_malloc().
Referenced by cclQuePop(), cclQueTrim(), and cclStackTrim().