TeoCCl library: list.h File Reference
list.h File Reference
List module.
Typedefs
typedef struct ccl_list ccl_list_t
typedef struct node iter_list_t
Functions
ccl_list_t * cclListInit (const size_t data_size)
int cclListCount (const ccl_list_t *dllist)
int cclListEmpty (const ccl_list_t *dllist)
iter_list_t * cclListGetIter (const ccl_list_t *dllist)
iter_list_t * cclListIterNext (iter_list_t *it)
void * cclListIterData (iter_list_t *it)
int cclListAddFirst (ccl_list_t *bllist, void *const data)
int cclListAddLast (ccl_list_t *bllist, void *const data)
int cclListAddAt (ccl_list_t *bllist, void *const data, const int idx)
int cclListGetFirst (ccl_list_t *bllist, void *const data)
int cclListGetLast (ccl_list_t *bllist, void *const data)
int cclListGetAt (ccl_list_t *bllist, const int idx, void *const data)
int cclListUpdateFirst (ccl_list_t *bllist, void *const data)
int cclListUpdateLast (ccl_list_t *bllist, void *const data)
int cclListUpdateAt (ccl_list_t *bllist, const int idx, void *const data)
int cclListRemoveFirst (ccl_list_t *bllist)
int cclListRemoveLast (ccl_list_t *bllist)
int cclListRemoveAt (ccl_list_t *bllist, const int idx)
void cclListClear (ccl_list_t *bllist)
void cclListDestroy (ccl_list_t *bllist)
void cclSortListAdd (ccl_list_t *bllist, void *data, int(*cmp)(const void *, const void *))
Detailed Description
List module.
double linked list module
Author
max mpano.nosp@m.91@g.nosp@m.mail..nosp@m.com
Array List container
Created on Fri Jun 1 17:01:30 2018
Author
max mpano.nosp@m.91@g.nosp@m.mail..nosp@m.com
double linked list container
Created on Tue Jul 11 19:55:30 2019
Typedef Documentation
typedef struct ccl_list ccl_list_t
typedef struct node iter_list_t
Function Documentation
int cclListAddAt (ccl_list_t * bllist, void *const data, const int idx)
References ccl_malloc().
Referenced by cclListAddFirst(), and cclListAddLast().
int cclListAddFirst (ccl_list_t * bllist, void *const data)
References cclListAddAt().
int cclListAddLast (ccl_list_t * bllist, void *const data)
References cclListAddAt().
void cclListClear (ccl_list_t * bllist)
Referenced by cclListDestroy().
int cclListCount (const ccl_list_t * dllist)
Referenced by cclListEmpty(), and cclListIterData().
void cclListDestroy (ccl_list_t * bllist)
References cclListClear().
int cclListEmpty (const ccl_list_t * dllist)
References cclListCount().
int cclListGetAt (ccl_list_t * bllist, const int idx, void *const data)
Referenced by cclListGetFirst(), and cclListGetLast().
int cclListGetFirst (ccl_list_t * bllist, void *const data)
References cclListGetAt().
iter_list_t* cclListGetIter (const ccl_list_t * dllist)
int cclListGetLast (ccl_list_t * bllist, void *const data)
References cclListGetAt().
ccl_list_t* cclListInit (const size_t data_size)
References ccl_malloc().
void* cclListIterData (iter_list_t * it)
References cclListCount().
iter_list_t* cclListIterNext (iter_list_t * it)
int cclListRemoveAt (ccl_list_t * bllist, const int idx)
Referenced by cclListRemoveFirst(), and cclListRemoveLast().
int cclListRemoveFirst (ccl_list_t * bllist)
References cclListRemoveAt().
int cclListRemoveLast (ccl_list_t * bllist)
References cclListRemoveAt().
int cclListUpdateAt (ccl_list_t * bllist, const int idx, void *const data)
Referenced by cclListUpdateFirst(), and cclListUpdateLast().
int cclListUpdateFirst (ccl_list_t * bllist, void *const data)
References cclListUpdateAt().
int cclListUpdateLast (ccl_list_t * bllist, void *const data)
References cclListUpdateAt().
void cclSortListAdd (ccl_list_t * bllist, void * data, int(*)(const void *, const void *) cmp)