TeoCCl library: lru_cache.h File Reference
lru_cache.h File Reference
#include <stdlib.h>
Typedefs
typedef struct ccl_lru_cache ccl_lru_cache_t
Functions
ccl_lru_cache_t * cclLruInit (const size_t size)
void cclLruDestroy (ccl_lru_cache_t *lru)
void cclLruRefer (ccl_lru_cache_t *lru, void *data, size_t data_len)
void cclLruForeach (ccl_lru_cache_t *lru, void(*fn)(const void *const data))
Typedef Documentation
typedef struct ccl_lru_cache ccl_lru_cache_t
Function Documentation
void cclLruDestroy (ccl_lru_cache_t * lru)
References teoQueueDestroy().
void cclLruForeach (ccl_lru_cache_t * lru, void(*)(const void *const data) fn)
References teoQueueData::data, teoQueueIteratorElement(), teoQueueIteratorNext(), and teoQueueIteratorReset().
ccl_lru_cache_t* cclLruInit (const size_t size)
References teoMapNew(), and teoQueueNew().
void cclLruRefer (ccl_lru_cache_t * lru, void * data, size_t data_len)
References teoQueueData::data, teoQueueData::data_length, teoMapAdd(), teoMapDelete(), teoMapGet(), teoQueueAddTop(), teoQueueRemove(), and teoQueueSize().