TeoCCl library: map.h File Reference
map.h File Reference
Map module.
#include <string.h>
#include <stdint.h>
#include "teoccl/queue.h"
Data Structures
struct teoMap
struct teoMapElementData
struct teoMapIterator
Macros
#define HASH_TABLE_SIZE 127
#define HASH_TABLE_INITVAL 77557755
Typedefs
typedef struct teoMap teoMap
typedef struct teoMapElementData teoMapElementData
typedef struct teoMapIterator teoMapIterator
typedef int(* teoMapForeachFunction) (teoMap *m, int idx, teoMapElementData *d, void *user_data)
Functions
void * teoMapGetFirst (teoMap *map, size_t *data_length)
Get first available element from hash table.
size_t teoMapSize (teoMap *map)
Get number of elements in TR-UPD map.
teoMap * teoMapNew (size_t size, int auto_resize_f)
Create new map.
void teoMapDestroy (teoMap *map)
Destroy map.
void teoMapClear (teoMap *map)
void * teoMapAdd (teoMap *map, void *key, size_t key_length, void *data, size_t data_length)
Add (or update) key data to the map.
void * teoMapGet (teoMap *map, void *key, size_t key_length, size_t *data_length)
Get key data from hash table.
int teoMapDelete (teoMap *map, void *key, size_t key_length)
Delete keys element from map.
teoMapIterator * teoMapIteratorNew (teoMap *map)
Create new map iterator.
teoMapIterator * teoMapIteratorReverseNew (teoMap *map)
Create new map reverse iterator.
int teoMapIteratorFree (teoMapIterator *map_it)
Destroy map iterator.
teoMapElementData * teoMapIteratorNext (teoMapIterator *map_it)
Get next maps element.
teoMapElementData * teoMapIteratorPrev (teoMapIterator *map_it)
Get previous maps element.
int teoMapForeach (teoMap *m, teoMapForeachFunction callback, void *user_data)
Loop through map and call callback function with index and data in parameters.
Detailed Description
Map module.
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on June 6, 2016, 12:26 PM
Macro Definition Documentation
#define HASH_TABLE_INITVAL 77557755
Referenced by teoMapClear().
#define HASH_TABLE_SIZE 127
Referenced by teo::Map::Map(), and teoMapClear().
Typedef Documentation
typedef struct teoMap teoMap
typedef struct teoMapElementData teoMapElementData
typedef int(* teoMapForeachFunction) (teoMap *m, int idx, teoMapElementData *d, void *user_data)
typedef struct teoMapIterator teoMapIterator
Function Documentation
void* teoMapAdd (teoMap * map, void * key, size_t key_length, void * data, size_t data_length)
Add (or update) key data to the map.
Parameters
map
key
key_length
data
data_length
Returns
Parameters
map Pointer to teoMapData
key Pointer to key
key_length Key length
data Pointer to data
data_length Data length
Returns
Data of added key or (void*)-1 at error
References teoMap::auto_resize_f, teoQueueData::data, teoMapElementData::data, teoMapElementData::data_length, teoMapElementData::hash, teoMap::hash_map_size, teoMapElementData::key_length, teoMap::length, teoMap::q, teoQueueAdd(), and teoQueueUpdate().
Referenced by teo::Map::add(), and teoMapNew().
void teoMapClear (teoMap * map)
Parameters
map
References teoMap::collisions, teoQueueData::data, teoMapElementData::data, teoMapElementData::data_length, teoMapElementData::hash, teoMap::hash_map_size, HASH_TABLE_INITVAL, HASH_TABLE_SIZE, teoMapElementData::key_length, teoMap::q, teoHashFast(), teoHashSuperFast(), teoQueueFree(), teoQueueIteratorFree(), teoQueueIteratorNew(), and teoQueueIteratorNext().
Referenced by teo::Map::mapClear().
int teoMapDelete (teoMap * map, void * key, size_t key_length)
Delete keys element from map.
Parameters
map Pointer to teoMapData
key Pointer to key
key_length Key length
Returns
Zero at success, or errors: -1 - keys element not found
References teoMap::auto_resize_f, teoMapElementData::hash, teoMap::hash_map_size, teoMap::length, teoMap::q, and teoQueueDelete().
Referenced by teo::Map::del().
void teoMapDestroy (teoMap * map)
Destroy map.
Parameters
map
map Pointer to teoMapData
References teoMap::hash_map_size, teoMap::q, and teoQueueDestroy().
Referenced by teo::Map::~Map().
int teoMapForeach (teoMap * m, teoMapForeachFunction callback, void * user_data)
Loop through map and call callback function with index and data in parameters.
Parameters
m Pointer to teoMap
callback Pointer to callback function teoMapForeachFunction
Returns
Number of elements processed
References teoMapIteratorFree(), teoMapIteratorNew(), and teoMapIteratorNext().
Referenced by teo::Map::foreach().
void* teoMapGet (teoMap * map, void * key, size_t key_length, size_t * data_length)
Get key data from hash table.
Parameters
map Pointer to teoMapData
key Pointer to key
key_length Key length
data_length [out] Pointer to data length
Returns
Data of selected key (may be NULL) or (void*)-1 if not found
References teoMapElementData::data_length.
Referenced by teo::Map::get().
void* teoMapGetFirst (teoMap * map, size_t * data_length)
Get first available element from hash table.
Parameters
map
data_length
Returns
Parameters
map Pointer to teoHashTdata
data_length [out] Pointer to returned data length (may be NULL)
Returns
Pointer to Data of first available element or (void*)-1 if not found
References teoMapIteratorFree(), teoMapIteratorNew(), and teoMapIteratorNext().
Referenced by teo::Map::getFirst().
int teoMapIteratorFree (teoMapIterator * map_it)
Destroy map iterator.
Parameters
map_it Pointer to teoMapIterator
Returns
Zero at success
References teoMapIterator::it, and teoQueueIteratorFree().
Referenced by teo::Map::iteratorFree(), teoMapForeach(), teoMapGetFirst(), and teoMapNew().
teoMapIterator* teoMapIteratorNew (teoMap * map)
Create new map iterator.
Parameters
map Pointer to teoMapData
Returns
Pointer to teoMapIterator or NULL at memory allocate error
References teoMapIterator::idx, teoMapIterator::it, teoMapIterator::map, teoMap::q, teoQueueIteratorNew(), and teoMapIterator::tmv.
Referenced by teo::Map::iterator(), teoMapForeach(), teoMapGetFirst(), and teoMapNew().
teoMapElementData* teoMapIteratorNext (teoMapIterator * map_it)
Get next maps element.
Parameters
map_it Pointer to teoMapIterator
Returns
Pointer to map element data teoMapValueData
References teoQueueData::data, teoMap::hash_map_size, teoMapIterator::idx, teoMapIterator::it, teoMapIterator::map, teoMap::q, teoQueueIteratorNext(), teoQueueIteratorReset(), and teoMapIterator::tmv.
Referenced by teo::Map::iteratorNext(), teoMapForeach(), teoMapGetFirst(), and teoMapNew().
teoMapElementData* teoMapIteratorPrev (teoMapIterator * map_it)
Get previous maps element.
Parameters
map_it Pointer to teoMapIterator
Returns
Pointer to map element data teoMapValueData
References teoQueueData::data, teoMapIterator::idx, teoMapIterator::it, teoMapIterator::map, teoMap::q, teoQueueIteratorPrev(), teoQueueIteratorReset(), and teoMapIterator::tmv.
Referenced by teo::Map::iterator_prev().
teoMapIterator* teoMapIteratorReverseNew (teoMap * map)
Create new map reverse iterator.
Parameters
map Pointer to teoMapData
Returns
Pointer to teoMapIterator or NULL at memory allocate error
References teoMap::hash_map_size, teoMapIterator::idx, teoMapIterator::it, teoMapIterator::map, teoMap::q, teoQueueIteratorNew(), and teoMapIterator::tmv.
Referenced by teo::Map::iteratorReverse().
teoMap* teoMapNew (size_t size, int auto_resize_f)
Create new map.
Parameters
size
auto_resize_f
Returns
Parameters
size Size of hash map (hash map resized automatically)
auto_resize_f Auto resize hash map
Returns
Pointer to teoMapData
References teoMap::auto_resize_f, teoMap::collisions, teoQueueData::data, teoMapElementData::data, teoQueueData::data_length, teoMapElementData::hash, teoMap::hash_map_size, teoMapElementData::key_length, teoMap::length, teoQueueData::next, teoQueueData::prev, teoMap::q, teoMapAdd(), teoMapIteratorFree(), teoMapIteratorNew(), teoMapIteratorNext(), teoQueueFree(), teoQueueNew(), teoQueueNewData(), and teoQueuePut().
Referenced by teo::Map::Map().
size_t teoMapSize (teoMap * map)
Get number of elements in TR-UPD map.
Parameters
map Pointer to teoMapData
Returns
Number of elements in TR-UPD map
References teoMap::length.
Referenced by teo::Map::size().