TeoCCl library: memory.h File Reference
memory.h File Reference
#include <stddef.h>
Functions
void * ccl_malloc (size_t)
void * ccl_calloc (size_t)
char * ccl_strdup (const char *)
char * ccl_strndup (const char *, size_t)
void * ccl_realloc (void *, size_t)
Function Documentation
void* ccl_calloc (size_t)
References ccl_malloc().
Referenced by cclArrayListNew(), and teoQueueNew().
void* ccl_malloc (size_t)
Referenced by ccl_calloc(), ccl_strndup(), cclArrayListNew(), cclDequeClear(), cclDequeInit(), cclDequePushBack(), cclDequePushFront(), cclDequeTrim(), cclLinkedListAddAt(), cclLinkedListInit(), cclListAddAt(), cclListInit(), cclQueInit(), cclStackInit(), teoMapAdd(), teoMapIteratorNew(), teoMapIteratorReverseNew(), teoMapNew(), teoQueueIteratorNew(), and teoQueueNewData().
void* ccl_realloc (void * , size_t)
Referenced by cclDequePushBack(), and cclDequePushFront().
char* ccl_strdup (const char *)
char* ccl_strndup (const char * , size_t)
References ccl_malloc().