TeoCCl library: que.h File Reference
que.h File Reference
#include <stdlib.h>
Typedefs
typedef struct ccl_queue ccl_queue_t
Functions
ccl_queue_t * cclQueInit (const size_t data_size)
int cclQueSize (ccl_queue_t *que)
int cclQueEmpty (ccl_queue_t *que)
int cclQueTrim (ccl_queue_t *que)
int cclQuePush (ccl_queue_t *que, void *const data)
int cclQuePop (ccl_queue_t *que, void *const data)
int cclQueFront (ccl_queue_t *que, void *data)
int cclQueBack (ccl_queue_t *que, void *data)
int cclQueClear (ccl_queue_t *que)
void cclQueDestroy (ccl_queue_t *que)
Detailed Description
Author
max mpano.nosp@m.91@g.nosp@m.mail..nosp@m.com
Created on Tue Jul 11 19:55:30 2019
Typedef Documentation
typedef struct ccl_queue ccl_queue_t
Function Documentation
int cclQueBack (ccl_queue_t * que, void * data)
References cclDequeGetLast().
int cclQueClear (ccl_queue_t * que)
References cclDequeClear().
void cclQueDestroy (ccl_queue_t * que)
References cclDequeDestroy().
int cclQueEmpty (ccl_queue_t * que)
References cclDequeEmpty().
int cclQueFront (ccl_queue_t * que, void * data)
References cclDequeGetFirst().
ccl_queue_t* cclQueInit (const size_t data_size)
References ccl_malloc(), and cclDequeInit().
int cclQuePop (ccl_queue_t * que, void *const data)
References cclDequePopFront(), cclDequeTrim(), and cclQueSize().
int cclQuePush (ccl_queue_t * que, void *const data)
References cclDequePushBack().
int cclQueSize (ccl_queue_t * que)
References cclDequeSize().
Referenced by cclQuePop().
int cclQueTrim (ccl_queue_t * que)
References cclDequeTrim().