TeoCCl library: queue.c File Reference
queue.c File Reference
#include <stdlib.h>
#include <string.h>
#include "teoccl/queue.h"
Functions
teoQueue * teoQueueNew ()
Create new Teo Queue.
int teoQueueDestroy (teoQueue *q)
Destroy Teo Queue.
int teoQueueFree (teoQueue *q)
Remove all elements from Teo queue.
size_t teoQueueSize (teoQueue *q)
Get number of elements in Teo queue.
teoQueueData * teoQueuePut (teoQueue *q, teoQueueData *qd)
Put (add, copy) existing queue record to the end of selected queue.
teoQueueData * teoQueueNewData (void *data, size_t data_length)
Create new teoQueueData buffer.
teoQueueData * teoQueueAdd (teoQueue *q, void *data, size_t data_length)
Add new element to the end of Teo queue.
teoQueueData * teoQueueAddTop (teoQueue *q, void *data, size_t data_length)
Add new element to the top of Teo queue.
teoQueueData * teoQueueAddAfter (teoQueue *q, void *data, size_t data_length, teoQueueData *qd)
Add new element after selected in qd field.
teoQueueData * teoQueueUpdate (teoQueue *q, void *data, size_t data_length, teoQueueData *qd)
Update element: remove selected and set new one to it place.
teoQueueData * teoQueueRemove (teoQueue *q, teoQueueData *qd)
Remove element from queue but not free it.
int teoQueueDelete (teoQueue *q, teoQueueData *qd)
Delete element from queue and free it.
int teoQueueDeleteFirst (teoQueue *q)
Delete first element from queue and free it.
int teoQueueDeleteLast (teoQueue *q)
Delete last element from queue and free it.
teoQueueData * teoQueueMoveToEnd (teoQueue *q, teoQueueData *qd)
Move element from this queue to the end of queue.
teoQueueData * teoQueueMoveToTop (teoQueue *q, teoQueueData *qd)
Move element from this queue to the top of queue.
teoQueueIterator * teoQueueIteratorNew (teoQueue *q)
Create new Teo Queue iterator.
teoQueueIterator * teoQueueIteratorReset (teoQueueIterator *it, teoQueue *q)
Reset iterator (or swith to new Queue)
teoQueueData * teoQueueIteratorNext (teoQueueIterator *it)
Get next element from Teo Queue iterator.
teoQueueData * teoQueueIteratorPrev (teoQueueIterator *it)
Get previous element from Teo Queue iterator.
teoQueueData * teoQueueIteratorElement (teoQueueIterator *it)
Get current Teo Queue iterator element.
int teoQueueIteratorFree (teoQueueIterator *it)
Free (destroy) Teo Queue iterator.
int teoQueueForeach (teoQueue *q, teoQueueForeachFunction callback, void *user_data)
Loop through queue and call callback function with index and data in parameters.
Function Documentation
teoQueueData* teoQueueAdd (teoQueue * q, void * data, size_t data_length)
Add new element to the end of Teo queue.
Parameters
q Pointer to existing Teo Queue
data Pointer to data of new element
data_length Length of new element data
Returns
Pointer to teoQueueData of added element
References teoQueueNewData(), and teoQueuePut().
Referenced by teo::Queue::add(), teoMapAdd(), teoQueueAddAfter(), and teoQueueAddTop().
teoQueueData* teoQueueAddAfter (teoQueue * q, void * data, size_t data_length, teoQueueData * qd)
Add new element after selected in qd field.
Parameters
q Pointer to existing Teo Queue
data Pointer to data of new element
data_length Length of new element data
qd Pointer to teoQueueData of existing element
Returns
References teoQueue::last, teoQueue::length, teoQueueData::next, teoQueueData::prev, teoQueueAdd(), teoQueueAddTop(), and teoQueueNewData().
Referenced by teo::Queue::addAfter().
teoQueueData* teoQueueAddTop (teoQueue * q, void * data, size_t data_length)
Add new element to the top of Teo queue.
Parameters
q Pointer to existing Teo Queue
data Pointer to data of new element
data_length Length of new element data
Returns
Pointer to teoQueueData of added element
References teoQueueAdd(), and teoQueueMoveToTop().
Referenced by teo::Queue::addTop(), and teoQueueAddAfter().
int teoQueueDelete (teoQueue * q, teoQueueData * qd)
Delete element from queue and free it.
Parameters
q Pointer to teoQueue
qd Pointer to teoQueueData
Returns
Zero at success
References teoQueueRemove().
Referenced by teo::Queue::del(), teoMapDelete(), teoQueueDeleteFirst(), and teoQueueDeleteLast().
int teoQueueDeleteFirst (teoQueue * q)
Delete first element from queue and free it.
Parameters
q Pointer to teoQueue
Returns
Zero at success
References teoQueue::first, and teoQueueDelete().
Referenced by teo::Queue::delFirst().
int teoQueueDeleteLast (teoQueue * q)
Delete last element from queue and free it.
Parameters
q Pointer to teoQueue
Returns
Zero at success
References teoQueue::last, and teoQueueDelete().
Referenced by teo::Queue::delLast().
int teoQueueDestroy (teoQueue * q)
Destroy Teo Queue.
Parameters
q Pointer to existing Teo Queue
Returns
Zero at success
References teoQueueFree().
Referenced by teoMapDestroy(), and teo::Queue::~Queue().
int teoQueueForeach (teoQueue * q, teoQueueForeachFunction callback, void * user_data)
Loop through queue and call callback function with index and data in parameters.
Parameters
q Pointer to teoQueue
callback Pointer to callback function teoQueueForeachFunction
Returns
Number of elements processed
References teoQueueIteratorElement(), teoQueueIteratorFree(), teoQueueIteratorNew(), and teoQueueIteratorNext().
Referenced by teo::Queue::foreach().
int teoQueueFree (teoQueue * q)
Remove all elements from Teo queue.
Parameters
q Pointer to existing Teo Queue
Returns
Zero at success
References teoQueue::first, and teoQueueData::next.
Referenced by teo::Queue::freeAll(), teoMapClear(), teoMapNew(), and teoQueueDestroy().
teoQueueData* teoQueueIteratorElement (teoQueueIterator * it)
Get current Teo Queue iterator element.
Parameters
it Pointer to teoQueueIterator
Returns
Pointer to the teoQueueData or NULL if not exists
References teoQueueIterator::qd.
Referenced by teo::Queue::iteratorElement(), and teoQueueForeach().
int teoQueueIteratorFree (teoQueueIterator * it)
Free (destroy) Teo Queue iterator.
Parameters
it Pointer to teoQueueIterator
Returns
Zero at success
Referenced by teo::Queue::iteratorFree(), teoMapClear(), teoMapIteratorFree(), and teoQueueForeach().
teoQueueIterator* teoQueueIteratorNew (teoQueue * q)
Create new Teo Queue iterator.
Parameters
q Pointer to teoQueue
Returns
References teoQueueIterator::q, and teoQueueIterator::qd.
Referenced by teo::Queue::iterator(), teoMapClear(), teoMapIteratorNew(), teoMapIteratorReverseNew(), and teoQueueForeach().
teoQueueData* teoQueueIteratorNext (teoQueueIterator * it)
Get next element from Teo Queue iterator.
Parameters
it Pointer to teoQueueIterator
Returns
Pointer to the teoQueueData or NULL if not exists
References teoQueue::first, teoQueueData::next, teoQueueIterator::q, and teoQueueIterator::qd.
Referenced by teo::Queue::iteratorNext(), teoMapClear(), teoMapIteratorNext(), and teoQueueForeach().
teoQueueData* teoQueueIteratorPrev (teoQueueIterator * it)
Get previous element from Teo Queue iterator.
Parameters
it Pointer to teoQueueIterator
Returns
Pointer to the teoQueueData or NULL if not exists
References teoQueue::last, teoQueueData::prev, teoQueueIterator::q, and teoQueueIterator::qd.
Referenced by teo::Queue::iteratorPrev(), and teoMapIteratorPrev().
teoQueueIterator* teoQueueIteratorReset (teoQueueIterator * it, teoQueue * q)
Reset iterator (or swith to new Queue)
Parameters
it Pointer to teoQueueIterator
q Pointer to teoQueue to switch to or NULL to reset current queue
Returns
Pointer to input teoQueueIterator
References teoQueueIterator::q, and teoQueueIterator::qd.
Referenced by teo::Queue::iteratorElement(), teoMapIteratorNext(), and teoMapIteratorPrev().
teoQueueData* teoQueueMoveToEnd (teoQueue * q, teoQueueData * qd)
Move element from this queue to the end of queue.
Parameters
q Pointer to teoQueue
qd Pointer to teoQueueData
Returns
Pointer to input teoQueueData
References teoQueue::last, teoQueue::length, teoQueueData::next, teoQueueData::prev, and teoQueueRemove().
Referenced by teo::Queue::moveToEnd().
teoQueueData* teoQueueMoveToTop (teoQueue * q, teoQueueData * qd)
Move element from this queue to the top of queue.
Parameters
q Pointer to teoQueue
qd Pointer to teoQueueData
Returns
Pointer to input teoQueueData
References teoQueue::first, teoQueue::length, teoQueueData::next, teoQueueData::prev, and teoQueueRemove().
Referenced by teo::Queue::moveToTop(), and teoQueueAddTop().
teoQueue* teoQueueNew ()
Create new Teo Queue.
Returns
Pointer to new Teo Queue or NULL if memory allocate error
Referenced by teo::Queue::Queue(), and teoMapNew().
teoQueueData* teoQueueNewData (void * data, size_t data_length)
Create new teoQueueData buffer.
Parameters
data Pointer to data
data_length Data length
Returns
References teoQueueData::data, and teoQueueData::data_length.
Referenced by teo::Queue::newData(), teoMapNew(), teoQueueAdd(), teoQueueAddAfter(), and teoQueueUpdate().
teoQueueData* teoQueuePut (teoQueue * q, teoQueueData * qd)
Put (add, copy) existing queue record to the end of selected queue.
Parameters
q Pointer to teoQueue
qd Pointer to teoQueueData
Returns
Zero at success
References teoQueue::first, teoQueue::last, teoQueue::length, teoQueueData::next, and teoQueueData::prev.
Referenced by teo::Queue::put(), teoMapNew(), and teoQueueAdd().
teoQueueData* teoQueueRemove (teoQueue * q, teoQueueData * qd)
Remove element from queue but not free it.
Parameters
q Pointer to teoQueue
qd Pointer to teoQueueData
Returns
Pointer to teoQueueData
References teoQueue::first, teoQueue::last, teoQueue::length, teoQueueData::next, and teoQueueData::prev.
Referenced by teo::Queue::remove(), teoQueueDelete(), teoQueueMoveToEnd(), and teoQueueMoveToTop().
size_t teoQueueSize (teoQueue * q)
Get number of elements in Teo queue.
Parameters
q
Returns
Number of elements in Teo queue
References teoQueue::length.
Referenced by teo::Queue::size().
teoQueueData* teoQueueUpdate (teoQueue * q, void * data, size_t data_length, teoQueueData * qd)
Update element: remove selected and set new one to it place.
Parameters
q Pointer to existing Teo Queue
data Pointer to data of new element
data_length Length of new element data
qd Pointer to teoQueueData of existing element
Returns
References teoQueue::first, teoQueue::last, teoQueueData::next, teoQueueData::prev, and teoQueueNewData().
Referenced by teoMapAdd().