TeoCCl library: stack.c File Reference
stack.c File Reference
#include "teoccl/memory.h"
#include "teoccl/deque.h"
#include "teoccl/stack.h"
Functions
ccl_stack_t * cclStackInit (size_t data_size)
int cclStackSize (ccl_stack_t *s)
int cclStackEmpty (ccl_stack_t *s)
int cclStackTrim (ccl_stack_t *s)
int cclStackPush (ccl_stack_t *s, void *const data)
int cclStackPop (ccl_stack_t *s, void *data)
int cclStackTop (ccl_stack_t *s, void *data)
int cclStackClear (ccl_stack_t *s)
void cclStackDestroy (ccl_stack_t *s)
Function Documentation
int cclStackClear (ccl_stack_t * s)
References cclDequeClear().
void cclStackDestroy (ccl_stack_t * s)
References cclDequeDestroy().
int cclStackEmpty (ccl_stack_t * s)
References cclDequeEmpty().
ccl_stack_t* cclStackInit (size_t data_size)
References ccl_malloc(), and cclDequeInit().
int cclStackPop (ccl_stack_t * s, void * data)
References cclDequePopBack().
int cclStackPush (ccl_stack_t * s, void *const data)
References cclDequePushBack().
int cclStackSize (ccl_stack_t * s)
References cclDequeSize().
int cclStackTop (ccl_stack_t * s, void * data)
References cclDequeGetLast().
int cclStackTrim (ccl_stack_t * s)
References cclDequeTrim().