TeoCCl library: stack.h File Reference
stack.h File Reference
#include <stdlib.h>
Typedefs
typedef struct ccl_stack ccl_stack_t
Functions
ccl_stack_t * cclStackInit (size_t data_size)
int cclStackSize (ccl_stack_t *s)
int cclStackEmpty (ccl_stack_t *s)
int cclStackTrim (ccl_stack_t *s)
int cclStackPush (ccl_stack_t *s, void *const data)
int cclStackPop (ccl_stack_t *s, void *data)
int cclStackTop (ccl_stack_t *s, void *data)
int cclStackClear (ccl_stack_t *s)
void cclStackDestroy (ccl_stack_t *s)
Detailed Description
Author
max mpano.nosp@m.91@g.nosp@m.mail..nosp@m.com
Created on Sut Sep 4 19:55:30 2019
Typedef Documentation
typedef struct ccl_stack ccl_stack_t
Function Documentation
int cclStackClear (ccl_stack_t * s)
References cclDequeClear().
void cclStackDestroy (ccl_stack_t * s)
References cclDequeDestroy().
int cclStackEmpty (ccl_stack_t * s)
References cclDequeEmpty().
ccl_stack_t* cclStackInit (size_t data_size)
References ccl_malloc(), and cclDequeInit().
int cclStackPop (ccl_stack_t * s, void * data)
References cclDequePopBack().
int cclStackPush (ccl_stack_t * s, void *const data)
References cclDequePushBack().
int cclStackSize (ccl_stack_t * s)
References cclDequeSize().
int cclStackTop (ccl_stack_t * s, void * data)
References cclDequeGetLast().
int cclStackTrim (ccl_stack_t * s)
References cclDequeTrim().