teoccl: main_t.c File Reference
main_t.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <CUnit/Basic.h>
Functions
int init_suite (void)
int clean_suite (void)
int queueSuiteAdd ()
Queue suite add.
int mapSuiteAdd ()
int listSuiteAdd ()
List suite add.
int main ()
Function Documentation
clean_suite()
int clean_suite (void)
References listSuiteAdd(), mapSuiteAdd(), and queueSuiteAdd().
Referenced by listSuiteAdd(), mapSuiteAdd(), and queueSuiteAdd().
init_suite()
int init_suite (void)
Referenced by listSuiteAdd(), mapSuiteAdd(), and queueSuiteAdd().
listSuiteAdd()
int listSuiteAdd ()
List suite add.
Returns
References clean_suite(), init_suite(), list_add_remove_test(), and list_create_test().
Referenced by clean_suite(), and main().
main()
int main ()
References listSuiteAdd(), mapSuiteAdd(), and queueSuiteAdd().
mapSuiteAdd()
int mapSuiteAdd ()
References check_binary_key(), check_hash(), check_map(), check_map_delete(), clean_suite(), and init_suite().
Referenced by clean_suite(), and main().
queueSuiteAdd()
int queueSuiteAdd ()
Queue suite add.
Returns
References add_elements_to_queue(), check_queue_iterator(), clean_suite(), delete_elements_from_queue(), init_suite(), and queue_create_test().
Referenced by clean_suite(), and main().