teoccl: map_t.c File Reference
map_t.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <CUnit/Basic.h>
#include <CUnit/CUnit.h>
#include "map.h"
#include "hash.h"
Macros
#define BUFFER_LEN 64
Functions
int init_suite (void)
int clean_suite (void)
long long timeInMilliseconds (void)
void check_hash ()
void _check_map (const size_t NUM_KEYS)
void check_map ()
void check_binary_key ()
void check_map_delete ()
int mapSuiteAdd ()
Variables
char ip_str [BUFFER_LEN]
Macro Definition Documentation
BUFFER_LEN
#define BUFFER_LEN 64
Function Documentation
_check_map()
void _check_map (const size_t NUM_KEYS)
References timeInMilliseconds().
Referenced by check_map().
check_binary_key()
void check_binary_key ()
References teoMapAdd(), teoMapDestroy(), teoMapGet(), and teoMapNew().
Referenced by mapSuiteAdd().
check_hash()
void check_hash ()
References teoHashFast(), and teoHashSuperFast().
Referenced by mapSuiteAdd().
check_map()
void check_map ()
References _check_map().
Referenced by mapSuiteAdd().
check_map_delete()
void check_map_delete ()
Referenced by mapSuiteAdd().
clean_suite()
int clean_suite (void)
Referenced by mapSuiteAdd().
init_suite()
int init_suite (void)
Referenced by mapSuiteAdd().
mapSuiteAdd()
int mapSuiteAdd ()
References check_binary_key(), check_hash(), check_map(), check_map_delete(), clean_suite(), and init_suite().
Referenced by clean_suite(), and main().
timeInMilliseconds()
long long timeInMilliseconds (void)
Referenced by _check_map().
Variable Documentation
ip_str
char ip_str[BUFFER_LEN]