teoccl: queue_t.c File Reference
queue_t.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <CUnit/Basic.h>
#include "queue.h"
Macros
#define NO_MESSAGES 1
#define NO_MESSAGES 1
#define NO_MESSAGES 1
#define NEXT next = teoQueueIteratorNext(it)
Functions
int init_suite (void)
int clean_suite (void)
void queue_create_test ()
Create/destroy Teo queue test.
void add_elements_to_queue ()
Add elements to Teo queue test.
void check_queue_iterator ()
Check Queue iterator.
void delete_elements_from_queue ()
Delete elements from Teo Queue.
int queueSuiteAdd ()
Queue suite add.
Macro Definition Documentation
NEXT
#define NEXT next = teoQueueIteratorNext(it)
Referenced by delete_elements_from_queue().
NO_MESSAGES [1/3]
#define NO_MESSAGES 1
NO_MESSAGES [2/3]
#define NO_MESSAGES 1
NO_MESSAGES [3/3]
#define NO_MESSAGES 1
Function Documentation
add_elements_to_queue()
void add_elements_to_queue ()
Add elements to Teo queue test.
References teoQueueData::data, teoQueueData::data_length, teoQueue::first, teoQueue::last, teoQueue::length, teoQueueData::next, teoQueueData::prev, teoQueueAdd(), teoQueueDeleteFirst(), teoQueueDeleteLast(), teoQueueDestroy(), teoQueueMoveToEnd(), teoQueueMoveToTop(), teoQueueNew(), teoQueueSize(), and teoQueueUpdate().
Referenced by queueSuiteAdd().
check_queue_iterator()
void check_queue_iterator ()
Check Queue iterator.
References teoQueueData::data, teoQueueData::data_length, teoQueueAdd(), teoQueueDestroy(), teoQueueIteratorElement(), teoQueueIteratorFree(), teoQueueIteratorNew(), teoQueueIteratorNext(), teoQueueNew(), and teoQueueSize().
Referenced by queueSuiteAdd().
clean_suite()
int clean_suite (void)
References listSuiteAdd(), mapSuiteAdd(), and queueSuiteAdd().
Referenced by queueSuiteAdd().
delete_elements_from_queue()
void delete_elements_from_queue ()
Delete elements from Teo Queue.
References teoQueueData::data, teoQueueData::data_length, NEXT, teoQueueAdd(), teoQueueDelete(), teoQueueDestroy(), teoQueueIteratorElement(), teoQueueIteratorFree(), teoQueueIteratorNew(), teoQueueIteratorNext(), teoQueueNew(), and teoQueueSize().
Referenced by queueSuiteAdd().
init_suite()
int init_suite (void)
Referenced by queueSuiteAdd().
queue_create_test()
void queue_create_test ()
Create/destroy Teo queue test.
References teoQueueDestroy(), and teoQueueNew().
Referenced by queueSuiteAdd().
queueSuiteAdd()
int queueSuiteAdd ()
Queue suite add.
Returns
References add_elements_to_queue(), check_queue_iterator(), clean_suite(), delete_elements_from_queue(), init_suite(), and queue_create_test().
Referenced by clean_suite(), and main().