TeoCCl: map.h File Reference
distr/install/usr/include/libteoccl/map.h File Reference
#include <string.h>
#include <stdint.h>
#include "queue.h"
Data Structures
struct teoMap
struct teoMapElementData
struct teoMapIterator
Macros
#define HASH_TABLE_SIZE 100
#define HASH_TABLE_INITVAL 77557755
Typedefs
typedef struct teoMap teoMap
typedef struct teoMapElementData teoMapElementData
typedef struct teoMapIterator teoMapIterator
typedef int(* teoMapForeachFunction) (teoMap *m, int idx, teoMapElementData *d, void *user_data)
Functions
void * teoMapGetFirst (teoMap *map, size_t *data_length)
Get first available element from hash table.
size_t teoMapSize (teoMap *map)
Get number of elements in TR-UPD map.
teoMap * teoMapNew (size_t size, int auto_resize_f)
Create new map.
void teoMapDestroy (teoMap *map)
Destroy map.
void teoMapClear (teoMap *map)
void * teoMapAdd (teoMap *map, void *key, size_t key_length, void *data, size_t data_length)
Add (or update) key data to the map.
void * teoMapGet (teoMap *map, void *key, size_t key_length, size_t *data_length)
Get key data from hash table.
int teoMapDelete (teoMap *map, void *key, size_t key_length)
Delete keys element from map.
teoMapIterator * teoMapIteratorNew (teoMap *map)
Create new map iterator.
teoMapIterator * teoMapIteratorReverseNew (teoMap *map)
Create new map reverse iterator.
int teoMapIteratorFree (teoMapIterator *map_it)
Destroy map iterator.
teoMapElementData * teoMapIteratorNext (teoMapIterator *map_it)
Get next maps element.
teoMapElementData * teoMapIteratorPrev (teoMapIterator *map_it)
Get previous maps element.
int teoMapForeach (teoMap *m, teoMapForeachFunction callback, void *user_data)
Loop through map and call callback function with index and data in parameters.
Macro Definition Documentation
HASH_TABLE_INITVAL
#define HASH_TABLE_INITVAL 77557755
HASH_TABLE_SIZE
#define HASH_TABLE_SIZE 100
Referenced by teo::Map::Map().
Typedef Documentation
teoMap
typedef struct teoMap teoMap
teoMapElementData
typedef struct teoMapElementData teoMapElementData
teoMapForeachFunction
typedef int(* teoMapForeachFunction) (teoMap *m, int idx, teoMapElementData *d, void *user_data)
teoMapIterator
typedef struct teoMapIterator teoMapIterator
Function Documentation
teoMapAdd()
void* teoMapAdd (teoMap * map, void * key, size_t key_length, void * data, size_t data_length)
Add (or update) key data to the map.
Parameters
map Pointer to teoMapData
key Pointer to key
key_length Key length
data Pointer to data
data_length Data length
Returns
Data of added key or (void*)-1 at error
Referenced by teo::Map::add(), and check_binary_key().
teoMapClear()
void teoMapClear (teoMap * map)
Referenced by teo::Map::mapClear().
teoMapDelete()
int teoMapDelete (teoMap * map, void * key, size_t key_length)
Delete keys element from map.
Parameters
map Pointer to teoMapData
key Pointer to key
key_length Key length
Returns
Zero at success, or errors: -1 - keys element not found
Referenced by teo::Map::del().
teoMapDestroy()
void teoMapDestroy (teoMap * map)
Destroy map.
Parameters
map Pointer to teoMapData
Referenced by check_binary_key(), and teo::Map::~Map().
teoMapForeach()
int teoMapForeach (teoMap * m, teoMapForeachFunction callback, void * user_data)
Loop through map and call callback function with index and data in parameters.
Parameters
m Pointer to teoMap
callback Pointer to callback function teoMapForeachFunction
Returns
Number of elements processed
Referenced by teo::Map::foreach().
teoMapGet()
void* teoMapGet (teoMap * map, void * key, size_t key_length, size_t * data_length)
Get key data from hash table.
Parameters
map Pointer to teoMapData
key Pointer to key
key_length Key length
data_length [out] Pointer to data length
Returns
Data of selected key (may be NULL) or (void*)-1 if not found
Referenced by check_binary_key(), and teo::Map::get().
teoMapGetFirst()
void* teoMapGetFirst (teoMap * map, size_t * data_length)
Get first available element from hash table.
Parameters
map Pointer to teoHashTdata
data_length [out] Pointer to returned data length (may be NULL)
Returns
Pointer to Data of first available element or (void*)-1 if not found
Referenced by teo::Map::getFirst().
teoMapIteratorFree()
int teoMapIteratorFree (teoMapIterator * map_it)
Destroy map iterator.
Parameters
map_it Pointer to teoMapIterator
Returns
Zero at success
Referenced by teo::Map::iteratorFree().
teoMapIteratorNew()
teoMapIterator* teoMapIteratorNew (teoMap * map)
Create new map iterator.
Parameters
map Pointer to teoMapData
Returns
Pointer to teoMapIterator or NULL at memory allocate error
Referenced by teo::Map::iterator().
teoMapIteratorNext()
teoMapElementData* teoMapIteratorNext (teoMapIterator * map_it)
Get next maps element.
Parameters
map_it Pointer to teoMapIterator
Returns
Pointer to map element data teoMapValueData
Referenced by teo::Map::iteratorNext().
teoMapIteratorPrev()
teoMapElementData* teoMapIteratorPrev (teoMapIterator * map_it)
Get previous maps element.
Parameters
map_it Pointer to teoMapIterator
Returns
Pointer to map element data teoMapValueData
Referenced by teo::Map::iterator_prev().
teoMapIteratorReverseNew()
teoMapIterator* teoMapIteratorReverseNew (teoMap * map)
Create new map reverse iterator.
Parameters
map Pointer to teoMapData
Returns
Pointer to teoMapIterator or NULL at memory allocate error
Referenced by teo::Map::iteratorReverse().
teoMapNew()
teoMap* teoMapNew (size_t size, int auto_resize_f)
Create new map.
Parameters
size Size of hash map (hash map resized automatically)
auto_resize_f Auto resize hash map
Returns
Pointer to teoMapData
Referenced by check_binary_key(), and teo::Map::Map().
teoMapSize()
size_t teoMapSize (teoMap * map)
Get number of elements in TR-UPD map.
Parameters
map Pointer to teoMapData
Returns
Number of elements in TR-UPD map
Referenced by teo::Map::size().