teoccl: list_t.c File Reference
list_t.c File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/time.h>
#include <CUnit/Basic.h>
#include "list.h"
Functions
int init_suite (void)
int clean_suite (void)
double timeInMilliSeconds (void)
void free_int_fn (void *pointer)
void list_create_test ()
void list_add_remove_test ()
int listSuiteAdd ()
List suite add.
Function Documentation
clean_suite()
int clean_suite (void)
Referenced by listSuiteAdd().
free_int_fn()
void free_int_fn (void * pointer)
Referenced by list_create_test().
init_suite()
int init_suite (void)
Referenced by listSuiteAdd().
list_add_remove_test()
void list_add_remove_test ()
References teoArrayListAdd(), teoArrayListDelIdx(), teoArrayListLength(), teoArrayListNew(), and timeInMilliSeconds().
Referenced by listSuiteAdd().
list_create_test()
void list_create_test ()
References free_int_fn(), teoArrayListFree(), and teoArrayListNew().
Referenced by listSuiteAdd().
listSuiteAdd()
int listSuiteAdd ()
List suite add.
Returns
References clean_suite(), init_suite(), list_add_remove_test(), and list_create_test().
Referenced by clean_suite(), and main().
timeInMilliSeconds()
double timeInMilliSeconds (void)
Referenced by list_add_remove_test().